### ISSUE TITLE
.zshrc and .bashrc missing from /etc/skel

### ISSUE THREAD

**Issue by Lynolix** [ARCHLabs/Archlabs-User-Home#39]
As per the title, the aforementioned config files are missing in the latest `archlabs-user-skel` package.

This could lead to issues with the latest `upgrade-archlabs` script as it points to non-existent files.

**Comment by natemaia** [comment]
I see, thanks for the heads up

I'll see what I can do about it
The reason they were removed was due to conflicting files provided by
```bash``` & ```grml-zsh-config```

We definitely will need to sort it regardless, not only the upgrade script, new user creation will rely on them being present as well
