### ISSUE TITLE
Openbox rc.xml SendToDesktop

### ISSUE THREAD

**Issue by onoma2** [ARCHLabs/Archlabs-User-Home#44]
Currently every SendToDesktop shortcut points to description number 1.

Not sure if it is an intended behavior.

**Comment by natemaia** [comment]
Not at all, thanks for the catch

**Comment by natemaia** [comment]
Fixed in 4188797e25c93ca27ba76613ed9695ffd85b62f8

**Comment by onoma2** [comment]
Cool, thank you
