### ISSUE TITLE
Issue with TTY1

### ISSUE THREAD

**Issue by Dobbie03** [ARCHLabs/Archlabs-User-Home#49]
Not sure if this is a bug, have a read here for full story

https://forum.archlabslinux.com/t/solved-need-help-trying-to-startup-without-lightdm/675/4

**Comment by natemaia** [comment]
I don't think this is a bug at all.

With a fresh AL install logging in once and running
```
systemctl disable lightdm.service
```
reboot, you'll be greeted by console on the next boot.

After this, installing `xorg-xinit`, and [following instructions here](https://wiki.archlinux.org/index.php/Xinit) will allow further customization of startup

**Comment by natemaia** [comment]
Closing
